name: Validate Pull Request

on:
  pull_request:
    paths:
    - 'API/Maddons.json'
    - 'API/ElvUI.json'
    - 'API/WeakAuras.json'
    - 'API/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Tests
      run: npx jest
